
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
python_files = ["test_*.py"]

[tool.ruff]
include = ["/**/*.py"] # starts at the location of pyproject.toml
indent-width = 2

[tool.ruff.format]
quote-style="double"
indent-style="space"
line-ending="lf"